### ISSUE TITLE
meteorological_visualizer.htmlをjsで生成する

### ISSUE THREAD

**Issue by ren-ozeki** [public-tatsuya-noyori/meteorological_visualizer#12]
meteorological_visualizer.htmlは現在全て手書き。
画面の変更などがあった時に、6回分修正が必要で手間がかかる。
コードでループ等を使用して生成するように変更する。

**Comment by public-tatsuya-noyori** [comment]
example/org2/meteorological_visualizer.htmlは色々変わると思います。また、example/org2/meteorological_visualizer.htmlに記載している変数も今後変わると思うので、「このjsで作成する」というissueよりも他のissueの対応の方が先かと思われますので、とりあえず、クローズにしておきます。
