### ISSUE TITLE
arrowimageryproviderの代替

### ISSUE THREAD

**Issue by ren-ozeki** [public-tatsuya-noyori/meteorological_visualizer#13]
作成するかは未定。
DataSource群のものに{x}/{y}/{z}のURLを渡せるようにすると実装がシンプルになるのでは？と思ったのでメモ。

今は機能を付け足そうとすると、
なんでもかんでもrequestImageに入れる必要があり、
もう少しスリムにしたい願望のため。

**Comment by public-tatsuya-noyori** [comment]
configPropertyTableを読み込むようにしたmeteorological_visualizer/example/org2/js/ArrowImageryProvider.jsでだいぶスリムになったと思うのでクローズにします。
