### ISSUE TITLE
chromeで開くと画面がちらつく[ issueの試し書き ]

### ISSUE THREAD

**Issue by slvr-dell** [public-tatsuya-noyori/meteorological_visualizer#3]
chromeでmeteorological_visualizerを起動すると、
画面がちらつく。

CPU稼働率が猛烈に上がるので、それが原因か？

**Comment by public-tatsuya-noyori** [comment]
口頭で話しましたが、↓辺りがヒントかもしれません。
https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/
