### ISSUE TITLE
描画要素の選択ができるようにする。

### ISSUE THREAD

**Issue by slvr-dell** [public-tatsuya-noyori/meteorological_visualizer#5]
描画要素(気温、風、気圧など)を選択できるようにする。

描画要素を変更した時に、データがない時にはNo Dataと表示する

**Comment by slvr-dell** [comment]
描画要素の選択機能を作成したが、一つの画面の要素を変更するだけなのに、画面全体がリフレッシュされてしまう。
選択した窓だけを更新するように実装を変更する必要あり

**Comment by ren-ozeki** [comment]
一つのwindowのみをリフレッシュするようにプログラムを変更した。
if文で無理やり分岐させているので、もう少しシンプルに出来そう
