### ISSUE TITLE
コンター図を描画する機能を追加

### ISSUE THREAD

**Issue by slvr-dell** [public-tatsuya-noyori/meteorological_visualizer#6]
現在のmeteorological_visualizerは点の描画のみが実装されている。
しかし、コンターで見たほうが分かりやすいものが多くある(e.g. 気圧)。
そのためコンター図で描画する機能を追加したい。

cesiumの中にある描画機能で実現できれば良いが、
難しい場合は d3.js などのほかの描画ライブラリの使用も考えている。

**Comment by public-tatsuya-noyori** [comment]
org2にコンターの例を追加しましたので、とりあえず、クローズにします。
