### ISSUE TITLE
設定ファイルから、描画する要素の選択項目などを作成するように変更

### ISSUE THREAD

**Issue by ren-ozeki** [public-tatsuya-noyori/meteorological_visualizer#8]
設定ファイル(https://github.com/public-tatsuya-noyori/meteorological_preprocessor/blob/master/src/meteorological_preprocessor/conf_bufr_to_arrow.csv)

を読み込んで、カテゴリや要素についてwebページ上で選択できるように変更?

**Comment by public-tatsuya-noyori** [comment]
csvを変換したarrow形式のconfigPropertyTableの設定ファイルから表示するサンプルをmeteorological_visualizer/example/org2に作成したのでクローズします。
