### ISSUE TITLE
描画要素選択機能のリファクタリング(#5 issueによる)

### ISSUE THREAD

**Issue by ren-ozeki** [public-tatsuya-noyori/meteorological_visualizer#9]
#5 によって描画機能の選択は可能になったが、
その際に、関数にflagを渡して動作を変更するなどを行なっており、周辺の整理が必要

**Comment by public-tatsuya-noyori** [comment]
要素選択よりも、propertyConfig.arrowのパスを含んだfeatureConfig.arrowを作って、このarrowを表示、選択できるようにするのが楽だと思いますので、このチケットをクローズにします。
